### PR TITLE
[fix] avoid ConcurrentModificationException on KryonetSBKingServer

### LINKED ISSUE #64: Fix ConcurrentModificationException
Someone probably connected while sending messages and the HashMap was modified during iteration causing this exception.
Possible fixes:
- Iterate only on immutable collections

```
Exception in thread "pool-2-thread-1" java.util.ConcurrentModificationException
	at java.base/java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.base/java.util.HashMap$ValueIterator.next(Unknown Source)
	at br.com.sbk.sbking.networking.kryonet.KryonetSBKingServer.sendAll(KryonetSBKingServer.java:101)
	at br.com.sbk.sbking.networking.kryonet.KryonetSBKingServer.sendGameModeOrStrainChooserAll(KryonetSBKingServer.java:131)
	at br.com.sbk.sbking.networking.server.SBKingServer.sendGameModeOrStrainChooserAll(SBKingServer.java:128)
	at br.com.sbk.sbking.networking.server.gameServer.MinibridgeGameServer.sendGameModeOrStrainChooserAll(MinibridgeGameServer.java:207)
	at br.com.sbk.sbking.networking.server.gameServer.MinibridgeGameServer.run(MinibridgeGameServer.java:88)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### PR DESCRIPTION
**Pull request by rulojuka**
Closes #64

### CODE REVIEW

File: src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetSBKingServer.java [hunk 1]
```diff
@@ -82,7 +77,18 @@ protected void onMessage(SBKingMessage message, ConnectionWithIdentifier connect
   }
 
   private void sendOneTo(SBKingMessage message, UUID playerIdentifier) {
-    this.sendOneTo(message, this.connections.get(playerIdentifier));
+    ConnectionWithIdentifier connectionToSend = this.connections.stream()
+        .filter(connection -> playerIdentifier.equals(connection.getIdentifier())).findFirst().orElse(null);
```
Comment (aateg) [inline src/main/java/br/com/sbk/sbking/networking/kryonet/KryonetSBKingServer.java:81]: Nice solution!
